apiVersion: v2
name: stayhub
description: A Helm chart for StayHub booking platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - booking
  - microservices
  - kafka
  - postgresql
home: https://stayhub.com
maintainers:
  - name: StayHub Team
    email: werbenhs@gmail.com

dependencies:
  - name: postgresql
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "19.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled