spring:
  application:
    name: search-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/stayhub_search}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}

server:
  port: ${PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.stayhub: INFO