# Working configuration for Property Service
spring:
  application:
    name: property-service
  
  # Disable problematic auto-configurations
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${PORT:8081}
  tomcat:
    max-threads: 20
    min-spare-threads: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.stayhub: DEBUG
    org.springframework.boot: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Railway profile
spring:
  config:
    activate:
      on-profile: railway

logging:
  level:
    root: INFO
    com.stayhub: INFO