spring:
  application:
    name: property-service
  
  # Database configuration for Railway PostgreSQL
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  
  # Cache configuration (using simple since Redis not available)
  cache:
    type: simple
  
  # Disable external service auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

server:
  port: ${PORT:8081}
  tomcat:
    max-threads: 100
    min-spare-threads: 10

# Management/Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  server:
    port: ${PORT:8081}

logging:
  level:
    root: INFO
    com.stayhub: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"