# Admin Server Configuration
spring:
  application:
    name: admin-server
  
  # Security settings
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
      
  # Mail settings for notifications (optional)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server configuration
server:
  port: ${PORT:8090}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Application info for Admin dashboard
info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Admin Server for StayHub platform
    version: 1.0.0

# Logging
logging:
  level:
    root: INFO
    de.codecentric.boot.admin: INFO
    com.stayhub: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"