spring:
  application:
    name: booking-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/stayhub_bookings}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.stayhub: INFO

# External service URLs
services:
  property:
    url: ${PROPERTY_SERVICE_URL:http://localhost:8081}