# Minimal configuration for debugging startup issues
spring:
  application:
    name: user-service
  
  # Disable problematic auto-configurations
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: ${PORT:8084}
  tomcat:
    max-threads: 20
    min-spare-threads: 2
    connection-timeout: 20000
  shutdown: graceful

# Minimal management configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Minimal logging
logging:
  level:
    root: INFO
    com.stayhub: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Railway profile - even more minimal
spring:
  config:
    activate:
      on-profile: railway

logging:
  level:
    root: INFO
    com.stayhub: INFO