# Minimal configuration for user service
spring:
  application:
    name: user-service
  
  # Spring Boot Admin Client Configuration
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8090}
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin123}
        instance:
          service-url: ${SERVICE_URL:http://localhost:8084}
          management-url: ${SERVICE_URL:http://localhost:8084}/actuator
          health-url: ${SERVICE_URL:http://localhost:8084}/actuator/health
          metadata:
            tags:
              environment: ${SPRING_PROFILES_ACTIVE:development}
              version: 1.0.0
              team: backend
  
  # Disable ALL auto-configurations that could cause issues
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  
  # CORS configuration
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      max-age: 3600

# Server configuration
server:
  port: ${PORT:8084}
  address: 0.0.0.0
  tomcat:
    max-threads: 10
    min-spare-threads: 2
    connection-timeout: 20000
  compression:
    enabled: true
  http2:
    enabled: true
  forward-headers-strategy: native

# Management/actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:development}

# Logging configuration
logging:
  level:
    root: INFO
    com.stayhub: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"