spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stayhub_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  security:
    user:
      name: admin
      password: admin

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics