# Absolute minimal configuration to test basic Spring Boot startup
spring:
  application:
    name: user-service
  
  # Disable ALL auto-configurations that could cause issues
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

# Minimal server configuration
server:
  port: ${PORT:8084}
  tomcat:
    max-threads: 10
    min-spare-threads: 2
    connection-timeout: 20000

# Minimal management/actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Verbose logging to see what's happening
logging:
  level:
    root: INFO
    com.stayhub: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"