spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/railway}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 10000
      validation-timeout: 5000
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Remove schema specification - use default schema
    show-sql: false

server:
  port: ${PORT:8084}
  tomcat:
    max-threads: 30
    connection-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  # Remove separate management server port - use main app port
  health:
    # Make health check less dependent on database
    db:
      enabled: false
    defaults:
      enabled: true

logging:
  level:
    com.stayhub: INFO
    org.springframework.boot: INFO
    org.hibernate.SQL: WARN
    root: WARN