spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/railway}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 10000
      validation-timeout: 5000
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
    show-sql: false

server:
  port: ${PORT:8084}
  tomcat:
    max-threads: 30
    connection-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: ${PORT:8084}  # Same port as main app

logging:
  level:
    com.stayhub: INFO
    org.springframework.boot: INFO
    root: WARN